### ISSUE TITLE
Handle connection failure in bundleInfo command

### ISSUE THREAD

**Issue by 2m** [sbt/sbt-typesafe-conductr#25]
* when there is no conductr
* when conductr stops while the bundleInfo is running

**Comment by huntc** [comment]
I think this has been address by #112, right @2m ?

**Comment by 2m** [comment]
Nope. This has not been addressed yet.

**Comment by ktoso** [comment]
Not sure if @2m meant the same thing, but I came here to open an issue about:

```
[reactive-maps] $ loadBundle file:/Users/ktoso/code/reactive-maps/target/typesafe-conductr/reactive-maps-1.0-SNAPSHOT-9bccab573b81a5038febdce6907b5dc0b13a864971527aa0841beca1798ab7ce.zip
[info] Loading bundle to ConductR ...
[trace] Stack trace suppressed: run last *:loadBundle for the full output.
```

<- without conductr running; It's an:

```
java.lang.RuntimeException: Problem loading the bundle: Connection failed.
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.conductr.sbt.SbtTypesafeConductR$$anonfun$loadBundleTask$1$$anonfun$apply$14$$anonfun$apply$15$$anonfun$com$typesafe$conductr$sbt$SbtTypesafeConductR$$anonfun$$anonfun$$anonfun$$loadBundle$1$1.apply(SbtTypesafeConductR.scala:144)
```

but would be nicer if it would log this info right away, instead of just throwing (so I don't have to type `last ...` in order to have any idea what happened.

**Comment by hseeberger** [comment]
@ktoso, are you sure that you don't get 

```
[info] Loading bundle to ConductR ...
[trace] Stack trace suppressed: run last *:loadBundle for the full output.
[error] (*:loadBundle) Problem loading the bundle: Connection failed.
[error] Total time: 0 s, completed Mar 23, 2015 4:02:46 PM
```

In other words you get the issue: "Problem loading the bundle: Connection failed."

**Comment by ktoso** [comment]
You're right, it's in the line below, I missed it. 
So a) I'm blind/tired and we don't care :wink: b) it's not the most prominent there, could be improved.

Not a biggie.

**Comment by hseeberger** [comment]
I played with it a little bit and I think it's the best we can get given how sbt works.
