### ISSUE TITLE
Quickstart is confusing - why are we using 0 as port

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt-typesafe-conductr#51]
This should be explained or the DSL improved.

The 0 there is a magic number there. It's not explained in the quickstart why we're using a weird port number (it is explained in one sentence once you dig through https://github.com/sbt/sbt-bundle). When I see something like "port -> port" instincts from other tools kick in and I say "oh yeah 9000 -> 9000", which is wrong.

It's typed DSL so it could be made something meaningful instead of 0. With conversions from int to this meaningful type. As in `Endpoint(DynamicallyAllocated, ...)`

**Comment by huntc** [comment]
Thanks for raising - can this be moved to the sbt-bundle project though, as that is where the doc and endpoint declaration lives. Thanks.

**Comment by ktoso** [comment]
It's about the quickstart.
